### ISSUE TITLE
Simple WebRTC: Can't see focus on Start Conference button

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/Demos-old#195]
https://developer.microsoft.com/en-us/microsoft-edge/testdrive/demos/simplewebrtc/

Somebody did this:

```css
.button:focus {
  outline: none;
}
```

:(
